import type { IAIService } from '../AIServiceInterface'
import type {
  BomSuggestRequest,
  BomSuggestResponse,
  ChatRequest,
  ChatResponse,
  ExplainRequest,
  ExplainResponse,
  HelpRequest,
  HelpResponse,
  SummarizeRequest,
  SummarizeResponse,
} from '../types'

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

function makeId() {
  return `msg-${Math.random().toString(36).slice(2, 10)}`
}

const HELP_TOPICS: Record<string, string> = {
  'command-center':
    'The Command Center is your home base — it surfaces business health, today\'s priorities, critical alerts, and AI recommendations in one screen so you never have to hunt through menus.',
  inventory:
    'Inventory tracks stock across every warehouse. Safety stock is the buffer you keep to absorb demand spikes; the reorder point is the stock level that triggers a new purchase order before you run out.',
  procurement:
    'Procurement recommendations are generated by comparing current inventory, forecasted demand, and supplier lead time — a purchase is suggested only when waiting would risk a stockout.',
  bom:
    'A Bill of Materials (BOM) lists every raw material and quantity needed to produce one unit of a product. Changing a BOM automatically updates material requirement calculations for that product.',
  setup:
    'The setup wizard walks you through configuring your company, warehouses, products, materials, suppliers, and calendar — everything Nexora needs to start generating relevant recommendations.',
  default:
    'I can help explain any screen in Nexora — try asking about inventory, procurement, BOM, suppliers, or reports.',
}

function pickHelpAnswer(section: string, question?: string): string {
  const key = section.toLowerCase()
  const base = HELP_TOPICS[key] ?? HELP_TOPICS.default!
  if (question) {
    return `${base}\n\nRegarding "${question}" — this is a mocked response; once the FastAPI Groq service is connected, this answer will be generated live from your actual data.`
  }
  return base
}

function respondToChat(req: ChatRequest): string {
  const lastUser = [...req.messages].reverse().find((m) => m.role === 'user')
  const text = (lastUser?.content ?? '').toLowerCase()

  if (text.includes('reorder') || text.includes('purchase') || text.includes('stock'))
    return 'Based on current inventory levels and supplier lead times, a few items are approaching their reorder point. Check the Procurement → Recommendations tab for the full list with reasoning and confidence scores.'
  if (text.includes('supplier') || text.includes('vendor'))
    return 'Vendor performance is scored on on-time delivery, quality, and price competitiveness. Open the Vendors module to compare suppliers side by side.'
  if (text.includes('forecast') || text.includes('demand'))
    return 'Demand forecasting will use ML models once the backend is connected. For now, trend charts on the Command Center reflect historical mock data patterns.'
  if (text.includes('health'))
    return 'Your overall business health score blends inventory, supplier, and forecast health. Visit AI Health Check for the full breakdown and recommended fixes.'
  if (text.includes('hello') || text.includes('hi'))
    return 'Hello! I\'m Nexora, your virtual procurement assistant. Ask me about inventory, purchase orders, suppliers, or anything else on this platform.'

  return 'This is a mocked Nexora response — once connected to the live Groq-powered service, I\'ll answer using your real business data. Try asking about inventory, procurement, or suppliers.'
}

export const mockAIAdapter: IAIService = {
  async chat(req: ChatRequest): Promise<ChatResponse> {
    await delay(500 + Math.random() * 400)
    return {
      message: {
        id: makeId(),
        role: 'assistant',
        content: respondToChat(req),
        createdAt: new Date().toISOString(),
      },
      suggestedFollowUps: [
        'What should I reorder this week?',
        'Which supplier has the best lead time?',
        'Explain my business health score',
      ],
    }
  },

  async explain(req: ExplainRequest): Promise<ExplainResponse> {
    await delay(450)
    return {
      explanation: `Here's a plain-English explanation of "${req.subject}": this figure is derived from current inventory, demand, and supplier data. Once the AI service is connected, this will be a live, data-grounded narrative instead of a template.`,
    }
  },

  async summarize(req: SummarizeRequest): Promise<SummarizeResponse> {
    await delay(450)

    const data = req.data as { overallScore?: number; categories?: { label: string; score: number; status: string; summary: string }[] }
    if (typeof data.overallScore === 'number' && Array.isArray(data.categories)) {
      const sorted = [...data.categories].sort((a, b) => a.score - b.score)
      const weakest = sorted[0]
      const strongest = sorted[sorted.length - 1]
      return {
        summary:
          `Your overall business health score is ${data.overallScore}/100. ` +
          `${weakest ? `${weakest.label} needs the most attention right now (${weakest.score}/100) — ${weakest.summary}` : ''} ` +
          `${strongest ? `On the positive side, ${strongest.label} is performing well at ${strongest.score}/100.` : ''} ` +
          `Review the categories below and the AI Action Center for specific recommended next steps.`,
      }
    }

    return {
      summary: `Summary of ${req.subject}: overall status looks stable with a few items worth reviewing. Connect the AI service for a fully data-driven narrative summary.`,
    }
  },

  async help(req: HelpRequest): Promise<HelpResponse> {
    await delay(350)
    return {
      answer: pickHelpAnswer(req.section, req.question),
      relatedArticles: ['Getting Started with Nexora', 'Understanding Reorder Points', 'How AI Recommendations Work'],
    }
  },

  async suggestBom(req: BomSuggestRequest): Promise<BomSuggestResponse> {
    await delay(600)

    const needle = `${req.productName} ${req.productCategory ?? ''}`.toLowerCase()
    const matched = req.availableRawMaterials.filter(
      (m) => needle.includes(m.category.toLowerCase()) || needle.includes(m.name.toLowerCase()) || m.category.toLowerCase() === (req.productCategory ?? '').toLowerCase(),
    )
    const pool = (matched.length > 0 ? matched : req.availableRawMaterials).slice(0, 4)

    return {
      materials: pool.map((m) => ({
        rawMaterialId: m.id,
        quantityPerUnit: Number((1 + Math.random() * 3).toFixed(2)),
        scrapPct: Number((2 + Math.random() * 6).toFixed(1)),
      })),
      notes: 'Mock suggestion — connect a real GROQ_API_KEY for live AI-drafted recipes.',
    }
  },
}
